# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('total_quantity', models.IntegerField()),
                ('total_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('line_total', models.FloatField()),
                ('invoice', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='invoice.Invoice')),
            ],
        ),
    ]
